#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
RUN dotnet --info

WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
RUN dotnet --info


ARG version=2022-01-01--13-00-00--WIP

ENV DEBIAN_FRONTEND noninteractive
ENV DEBCONF_NOWARNINGS="yes"
RUN apt-get update
RUN apt-get install --no-install-recommends --yes apt-utils python3 npm
RUN dotnet --info
RUN dotnet workload install wasm-tools

WORKDIR /src
COPY ["Website.Server/Website.BlazorServer.csproj", "Website.Server/"]
COPY ["Website.Server/NuGet.Config", "Website.Server/"]

COPY ["Website.Client/Website.Client.csproj", "Website.Client/"]
COPY ["Website.WASM/Website.WASM.csproj", "Website.WASM/"]

RUN dotnet restore --disable-parallel "Website.Server/Website.Server.csproj"
COPY . .
WORKDIR "/src/Website.Server"
RUN dotnet publish "Website.Server.csproj" -c Release_WebAssembly -o /app/publish -p:Version=$version

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "Website.Server.dll"]