name: GithubActionsWIP

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]




env:
  project: 'Website.Server/Website.Server.csproj'
  blazorServerAppName: 'website-2203-blazor-server-wip'
  blazorWebAssemblyAppName: 'website-2203-blazor-webassembly-wip'
  registryName: 'dioptraregistry'
  registryLocation: 'uk south'
  blazorServerDockerFile: './Website.Server/Dockerfile-Server'
  blazorWebAssemblyDockerFile: './Website.Server/Dockerfile-WebAssembly'



jobs:

############################################################################################################
# These jobs are used to gate actions. By creating these jobs we don't need to proliferate the repo checks
############################################################################################################
  perform-deployment:
    name: Perform deployment because running on Dioptra/Website.2203 and user is not dependabot?
    runs-on: ubuntu-latest
    if: github.repository == 'Dioptra/Website.2203' && github.actor != 'dependabot[bot]'
    steps:
    - name: Nothing to see here
      run: echo ""

  skip-deployment:
    name: Skip deployment because not running on Dioptra/Website.2203 or user is dependabot?
    runs-on: ubuntu-latest
    if: github.repository != 'Dioptra/Website.2203' || github.actor == 'dependabot[bot]'
    steps:
    - name: Nothing to see here
      run: echo ""


############################################################################################################
# Set unified suffix for the two deployed applications
############################################################################################################
  set-suffix:
    name: Create the date based suffix
    needs: [perform-deployment]
    runs-on: ubuntu-latest
    outputs:
      outputSuffix: ${{ steps.setSuffix.outputs.GlobalSuffix }}

    steps:
    - id: setSuffix
      run: echo "GlobalSuffix=$(date +'%Y-%m-%d--%H-%M-%S')--WIP" >> $GITHUB_OUTPUT
      shell: bash

############################################################################################################
# Build blazor server on forks
############################################################################################################
  build-blazor-server-fork:
    name: Build BlazorServer for forks/dependabot
    needs: [skip-deployment]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository under $GITHUB_WORKSPACE so the job can access it 🛎️
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'
        include-prerelease: true

    - name: 'Build SSB'
      run: |
        dotnet build  ${{env.project}} --configuration Release_Server
   

############################################################################################################
# Build blazor webassembly on forks
############################################################################################################
  build-blazor-webassembly-fork:
    name: Build BlazorWASM for forks/dependabot
    needs: [skip-deployment]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository under $GITHUB_WORKSPACE so the job can access it 🛎️
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'
        include-prerelease: true

    - name: 'Build CSB'
      run: |
        dotnet build ${{env.project}} --configuration Release_WebAssembly
        

############################################################################################################
# Build blazor server container on Dioptra
############################################################################################################
  build-blazor-server:
    name: Build BlazorServer
    needs: [set-suffix]
    runs-on: ubuntu-latest

    steps:
    - name: Retrieve the global suffix
      run: echo "suffix=${{needs.set-suffix.outputs.outputSuffix}}" >> $GITHUB_ENV
      shell: bash

    - name: Checkout repository under $GITHUB_WORKSPACE so the job can access it 🛎️
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'
        include-prerelease: true

    - name: 'Build and push docker container'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    #- run: |
    #    dotnet workload install wasm-tools
    #    dotnet publish ${{env.project}} --os linux --arch x64 --configuration Release_Server -p:PublishProfile=DefaultContainer -p:Version=${{ env.suffix }} -p:ContainerImageName=${{env.blazorServerAppName}}
    #    docker tag ${{env.blazorServerAppName}}:${{ env.suffix }} ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{env.blazorServerAppName}}:${{ env.suffix }}
    #    docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{env.blazorServerAppName}}:${{ env.suffix }}
        
    - run: |
        docker build . --file ${{ env.blazorServerDockerFile }} --tag ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.blazorServerAppName }}:${{ env.suffix }} --build-arg version=${{ env.suffix }}
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.blazorServerAppName }}:${{ env.suffix }}


############################################################################################################
# Build blazor webassembly container on Dioptra
############################################################################################################
  build-blazor-webassembly:
    name: Build BlazorWASM
    needs: [set-suffix]
    runs-on: ubuntu-latest

    steps:
    - name: Retrieve the global suffix
      run: echo "suffix=${{needs.set-suffix.outputs.outputSuffix}}" >> $GITHUB_ENV
      shell: bash

    - name: Checkout repository under $GITHUB_WORKSPACE so the job can access it 🛎️
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'
        include-prerelease: true

    - name: 'Build and push docker container'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    #- run: |
    #    dotnet workload install wasm-tools
    #    dotnet publish ${{env.project}} --os linux --arch x64 --configuration Release_WebAssembly -p:PublishProfile=DefaultContainer -p:Version=${{ env.suffix }} -p:ContainerImageName=${{env.blazorServerAppName}}
    #    docker tag ${{env.blazorServerAppName}}:${{ env.suffix }} ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{env.blazorServerAppName}}:${{ env.suffix }}
    #    docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{env.blazorServerAppName}}:${{ env.suffix }}

    - run: |
        docker build . --file ${{ env.blazorWebAssemblyDockerFile }} --tag ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.blazorWebAssemblyAppName }}:${{ env.suffix }} --build-arg version=${{ env.suffix }}
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.blazorWebAssemblyAppName }}:${{ env.suffix }}

